# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: The Pixel Forge
title-normal: The Pixel Forge
email: info@thepixelforge.co.uk
description: The Pixel Forge is a Software, Mobile &amp; Web development company creating high performance, robust &amp; versatile solutions
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thepixelforge.co.uk" # the base hostname & protocol for your site
author: The Pixel Forge
building_name: Holland Court
street_address: Bisazza St
city: Sliema
state:
zip_code: SLM 1641
country: Malta
phone: (356) 7926 5592

# Plugins
gems:
  - jekyll-admin
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages" 
tiles-count: 6

# Social settings
500px_url: 
facebook_url: https://www.facebook.com/PixelForgeUK/
github_url: http://github.com/anth12
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/anthonyhalliday/
pinterest_url: 
slack_url: 
twitter_url: https://twitter.com/PixelForgeUk

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: PixelForgeUK
# Add one or more of the following
facebook:
  app_id: 
  publisher: 
  admins: 
logo: assets/images/site-image.jpg
google_site_verification: 
